[pytest]

markers =
    smoke: Tests included in the Smoke suite
    view_price: view pricebook changes
    viewprice:  view pricebook changes
    new_price_book: new price book changes
    logout: Logout feature
    createConfigPichedRoofing: create Pitched Roofting scoping configuration
    madarasu: test
    flatroofing: Scope configuration flat roofting
    exteriorpainting: Scope configuration for Exterior Painting
    doors: Scope configuration Doors
    carpentry: Scope configuration Carpentry
    siding: Scope configuration Siding
    interiorpainting: scope configuration for Interior painting
    windows: Scope configuration for windows
    pricebook: new price book changes
    regression: Tests included in the Regression suite
    issue: Testcase having issue
    order: Tests included in the Regression suite
    restock: Tests included in the Regression suite
    patient: Tests included in the Regression suite
    loginlogout: Tests included in the Regression suite
    appointmentdispense : Tests included in the Regression suite
    login : Tests included in the Regression suite
    pitchedroofing : Scope configuration Pitched Roofing
    login_pb: mark the test as related to the login process
    login_10: mark the test as related to the login process
    login_leads: mark the test as related to the login process
    login_leads_navbar: mark the test as related to the login process
    login_leads_navbar_filter: mark the test as related to the login process
    test_filter: mark the test as related to the login process
    login_add_leads: mark the test as related to the login process
    login_interact_with_lead_row: mark the test as related to the login process
    login_opportunities_navbar: mark the test as related to the login process
    login_contacts: mark the test as related to the login process
    login_opportunities_actions: mark the test as related to the login process
    test_filter_ba: mark the test as related to the login process
    login_leads_navbar_bulk_action: mark the test as related to the login process
    login_add_leads_self_gen: to add lead by selecting "Self gen" from lead type dropdown and assert if opprtunity is created
    login_add_leads_action_convert_as_opportunity: to add lead and convert as opportunity in actions
    login_add_leads_action_mark_as_dead: to add lead and mark as dead in actions
    login_opportunities_s_b: to add lead and mark as dead in actions
    login_add_leads_action_disqualify_lead: to disqualify lead while adding lead
    scope_config: scope_config
    upriceproductflat: Uprice Settings Product Flat Roofing
    upriceproductpitched: Uprice Settings Product Pitched Roofing
    upriceproductwindows: Uprice Settings Product Windows
    upriceproductdoors: Uprice Settings Product Doors
    upriceproductsiding: Uprice Settings Product Siding
    upriceproductinterior: Uprice Settings product Interior Painting
    upriceproductexterior: Uprice Settings product Exterior Painting
    upriceproductcarpentry: Uprice Settings Product Carpentry
	upriceproductmiscellaneous: Uprice Settings Product Miscellaneous
	upricesectionpitched: Uprice Settings Section Pitched
    upricesectionflat: Uprice Settings Section Flat
    upricesectionwindows: Uprice Settings Section Windows
    upricesectiondoors: Uprice Settings Section Doors
    upricesectionsiding: Uprice Settings Section Siding
    upricesectionsinteriorpaint: Uprice Settings Section Interior Paint
    upricesectionsexteriorpaint: Uprice Settings Section Exterior Paint
    upricesectionscarpentry: Uprice Settings Section Carpentry
    upricesectionsmiscellaneous: Uprice Settings Section Miscellaneous
    upricesubsectionpitched: Uprice Settings Sub Section Pitched Roofing
    upricesubsectionflat: Uprice Settings Sub Section Flat Roofing
    upricesubsectionwindows: Uprice Settings Sub Section Windows
    upricesubsectiondoors: Uprice Settings Sub Section Doors
    upricesubsectionsiding: Uprice Settings Sub Section Siding
    upricesubsectioninterior: Uprice Settings Sub Section Interior Painting
    upricesubsectionexterior: Uprice Settings Sub Section Exterior Painting
    upricesubsectioncarpentry: Uprice Settings Sub Section Carpentry
    upricesubsectionmiscellaneous: Uprice Settings Sub Section Miscellaneous
    upricemanufacturers: Uprice Settings Manufacturers
    upricebrand: Uprice Settings Brand
    upriceuoms: Uprice Settings UOMS
    upricecolor: Uprice Settings Color
    upricegeographicalhierarchy: Uprice Settings Uprice Geographical Hierarchy
    upricegeographicalhierarchydistrict: Uprice Settings Uprice Geographical Hierarchy District
    upricegeographicalhierarchyarea: Uprice Settings Uprice Geographical Hierarchy Areas
    upricegeographicalhierarchyzipcode: Uprice Settings Uprice Geographical Hierarchy Zip Code
    gallerypitchedroofing: Uprice Gallery Pitched Roofing
    galleryflatroofing: Uprice Gallery Flat Roofing
    gallerywindows: Uprice Gallery Windows
    gallerydoors: Uprice Gallery Doors
    gallerysiding: Uprice Gallery Siding
    galleryinteriorpaint: Uprice Gallery Interior Paint
    galleryexteriorpaint: Uprice Gallery Exterior Paint
    gallerycarpentry: Uprice Gallery Carpentry
    gallerymiscellaneous: Uprice Gallery Miscellaneous
    uquotesproductpitchedroofing: Uquote Product Pitched Roofing
    uquotesproductflatroofing: Uquote Product Flat Roofing
    uquotesproductwindow: Uquote Product Windows
    uquotesproductdoors: Uquote Product Doors
    uquotesproductsiding: Uquote Product Siding
    uquotesproductinterior: Uquote Product Interior
    uquotesproductexterior: Uquote Product Exterior
    uquotesproductcarpentry: Uquote Product Carpentry
    uquotessectionpitchedroofing: Uquote Section Pitched Roofing
    uquotessectionflatroofing: Uquote section Flat Roofing
    uquotessectionwindows: Uquote section Windows
    uquotessectiondoors: Uquote section Doors
    uquotessectionsiding: Uquote Section Siding
    uquotessectioninterior: Uquote Section Interior Paint
    uquotessectionexterior: Uquote Section Exterior Paint
    uquotesectioncarpentry: Uquote Section Carpentry
    uquotessubsectionpitchedroofing: Uquote Sub Section Pitched Roofing
    uquotessubsectionflatroofing: Uquote Sub Section Pitched Roofing
    uquotessubsectionwindows: Quote Sub Section Windows
    uquotessubsectiondoors: Quote Sub Section Doors
    uquotessubsectionsiding: Quote Sub Section Siding
    uquotessubsectionip: Quote Sub Section IP
    uquotessubsectionep: Quote Sub Section EP
    uquotessubsectioncarpentry: Quote Sub Section Carpentry
    pdfconfigurepr: PDF configure Pitched Roofing
    pdfconfigurefr: PDF configure Flat Roofing
    pdfconfigurewindows: PDF Configure Windows
    pdfconfigureexterior: PDF Configure Exterior Paint
    pdfconfigureinterior: PDF Configure Interior Paint
    pdfconfiguresiding: PDF Configure Siding
    pdfconfigurecarpentry: PDF Configure Carpentry
    pdfconfiguredoors: PDf Configure Doors
    userroles: configure User roles
    userfilters: Configure User filters
    ubaselead: Configure Ubase Lead
    scopeconfiguration: Scope configuration
    newuser: create new user
    appointment: Appointment module changes
    events: Event module changes
    viewpricephase3: View Pricebook Phase3
    pitchedroofingphase3: Pitched Roofing Phase 3
    flatdroofingphase3: Flat Roofing Phase 3
    windowsphase3: Windows Phase 3
    doorphase3: Doors Phase3
    exteriorpaintphase3: Exterior Paint Phase3
    interiorpaintphase3: Interior Paint Phase3
    sidingphase3: Siding Phase3
    carpentryphase3: Carpentry Phase3
    uquotesproductpr: Uquotes Product PR
    uquotesproductfr: Uquotes Product FR
    uquotesproductwindows: Uquotes Product Windows
    uquotesproductdoorsphase3: Uquotes Product Doors
    uquotesproductsidingphase3: Uquotes Product Siding
    uquotesproductcarpentryphase3: Uquotes Product Carpentry
    uquotesproductinteriorpaintphase3: Uquotes Product Interior Paint
    uquotessectionprphase3: Uquotes Section PR Phase3
    uquotessectionfrphase3: Uquotes Section FR Phase3
    uquotessectionwindowsphase3: Uquotes Section Windows Phase3
    uquotessectiondoorsphase3: Uquotes Section Doors Phase3
    uquotessectionsidingphase3: Uquotes Section Siding Phase3
    uquotessectioninteriorphase3: Uquotes Section Interior Paint Phase3
    uquotessectionexteriorphase3: Uquotes Section Exterior Paint Phase3
    uquotessectioncarpentryphase3: Uquotes Section Carpentry Phase3
    upricesubsectionprphase3: Uprices Sub Section Pitched Roofing Phase3
    upricesubsectionfrphase3: Uprices Sub Section Flat Roofing Phase3
    upricesubsectionwindowsphase3: UPrice Sub Section Windows Phase3
    uquotesubsectiondoorsphase3: Uquotes Sub Section Doors Phase3
    uquotesubsectionsidingphase3: Uquotes Sub Section siding Phase3
    uquotessubsectionipphase3: Uquotes Sub Section IP Phase3
    uquotessubsectionepphase3: Uquotes Sub Section EP Phase3
    uquotessubsectioncarpentryphase3: Uquotes Sub Section Carpentry
    upriceproductprphase3: UPrice Products Pitched Roofing
    upriceproductfrphase3: UPrice Products Flat Roofing
    upriceproductwindowsphase3: Uprice Products Windows
    upriceproductdoorsphase3: Uprice Products Doors
    upriceproductsidingphase3: Uprice Products Siding
    upriceproductipphase3: Uprice Products IP
    upriceproductepphase3: Uprice Products EP
    upriceproductcarpentryphase3: Uprice Products Carpentry
    upricesectionprphase3: Uprice Section Pitched Roofing
    upricesectionfrphase3: Uprice Section Flat Roofing
    upricesectionwindowsphase3: Uprice Section Windows
    upricesectiondoorsphase3: Uprice Section Doors
    upricesectionsidingphase3: Uprice Section Siding
    upricesectionipphase3: Uprice Section Interior Paint
    upricesectionepphase3: Uprice Section Exterior Paint
    upricesectioncarpentryphase3: Uprice Section Carpentry
    upricesubsectionprphase3: Uprice Sub Section PR
    uquotesubsectionprphase3 : Uquote Sub Section PR
    uquotessubsectionfrphase3: Uquote Sub Section FR
    uquotesubsectionwindowsphase3: Uquote Sub Section Windows
    upricesubsectiondoorsphase3: Uprice Sub Section Doors
    upricesubsectionsidingsphase3: Uprice Sub Section Siding
    upricesubsectionipphase3: Uprice Sub Section Interior Paint
    upricesubsectionepphase3: Uprice Sub Section Exterior Paint
    upricesubsectioncarpentryphase3: Uprice Sub Section Carpentry
    upricemanufacturersphase3: Uprice Manufactures Phase3
    upricebrandphase3: Uprice Brand Phase3
    upricecolorphase3: Uprice Color Phase3
    upricegeoghrregionphase3: Uprice Geographical Hierarchy Region Phase3
    upriceghdphase3: Uprice Geographical Hierarchy District Phase3
    upriceghaphase3: Uprice Geographical Hierarchy Areas Phase3
    module(name): specify the module name for the test (e.g., "Login")
    upriceghzphase3: Uprice Geographical Hierarchy Zip Code Phase3
    otherleadsourceshortphase3: Others Lead Source Short
    otherleadsourcelongphase3: Others Lead Source Long
    otherpromotorphase3: Others Promotors
    newpricebookprphase3: New Price Book Pitched Roofing
    newpricebookfrphase3: New Price Book Flat Roofing
    newpricebookwindowsphase3: New Price Book for Windows
    newpricebookdoorsphase3: New Price Book For Doors
    newpricebooksidingphase3: New Price Book For Siding
    newpricebookipphase3: New Price Book For Interior Paint
    newpricebookepphase3: New Price Book For Exterior Paint
    newpricebookcarpentryphase3: New Price Book For Carpentry
    mycalendarphase3: My Calendar changes for phase3
    salescalendarphase3: Sales Calendar Changes for phase3
    invoicephase3: Invoice Phase3
    accountsphase3: Accounts Phase3
    appointment1: tests
    jobs: Job module Phase3
    globalsearchphase3: Global Search Phase3
    campaignsphase3: Campaigns Phase3
    reportsphase3: Reports Module
    marketingdashboard: Marketing Dashboards
    marketingmangerdashboard: Marketing Manager Dashboard
    viewpricebook3: View Price Book Phase3
    marketingkpi: Marketing KPI Dashboard
    salesdashboard: Sales Dashboard
    salesmanagerdashboard: Sales Manager Dashboard
    add_estimate: add estimate
    summarycommissions: Summary Commissions
    upcomingpayroll: Commission Upcoming Payroll
    financedashboard: Finance Dashboard
    withdrawalrequests: Withdrawal Requests
    balancestatement: Balance Statement
    withdrawal_preferences: Withdrawal Preferences
    eventsreports: Events Reports
    uquotessubsectioncarpentryphase3: Uquotes Sub Section Carpentry Phase3
    commissionbonusschedules: Commission Bonus Schedules
    eventsactivityreports: Events Activity Reports
    rehashreports: Rehash Reports
    locationreports: Location Reports
    balancestatementnew: Commission module Balance Statement
    openinvoicereports: Open Invoice Reports
    financereport: Finance Report
    marketingreport: Marketing Report
    affiliatereport: Affiliate Report
    quickbooks: Quick Book Invoice
    printegrationflow: Pitched Roofing Integration Flow
    lsintegrationflow: Low Roofing Integration Flow
    windowsintegrationflow: Windows Integration Flow
    doorsintegrationflow: Doors Integration Flow
    epintegrationflow: Exterior Paint Integration Flow
    promoterpayrollreports: Promoter Payroll Reports
    ipintegrationflow: Interior Paint Full Flow
    sidingintegrationflow: Siding Integration Full Flow
    carpentryintegrationflow: Carpentry Integration Full Flow
    allpricebookcreation: Create All Price Book Changes
    prlowcombination: Create PR and Low Combination
    windowsddoorscombination: Windows & Doors Combinations
    ipepcombination: Interior & Exterior Combinations
    carpentrysidingcombination: Carpentry & Siding Combinations
    prlowexteriorcombination: Pitched, Low and Exterior Paint Combination
    prlowsidingcombination: Pitched, Low and Siding Combination
    ipepsidingcombination: Exterior, Interior and Siding Combination
    windowdoorsidingcombination: Windows, Doors and Siding Combination
    pitchedwindowsidingcombination: Pitched Windows and Siding Combination
    prlripepcombination: Pitched, Low , IP and EP Combination
    prlrwpdpcombination: Pitched, Low , Windows and Doors Combination
    prlrwpepcombination: Pitched, Low, Window and Exterior Combination
    prspwpepintegration: Pitched, Siding, Window and Exterior Combination
    allservicescombination: All Services Full Flow Combinations
    estimation: Estimation module changes






	
#addopts = --template=html1/index.html --report=./reports/report.html
#addopts = --html=UHE_Phase3_Report.html --self-contained-html --report=./Reports/report.html
addopts = --html=reports/UHE_Phase3_Report.html --self-contained-html --report=./reports/report.html
