[pytest]

markers =
    smoke: Tests included in the Smoke suite
    
    logout: Logout feature
    login: Login Feature 
	module(name): specify the module name for the test (e.g., "Login")
	accountsphase3: Account Page






	
#addopts = --template=html1/index.html --report=./reports/report.html
#addopts = --html=UHE_Phase3_Report.html --self-contained-html --report=./Reports/report.html
addopts = --html=reports/UHE_Report.html --self-contained-html --report=./reports/report.html
